### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by usefrancisco3210** [cyberjunky/home-assistant-garmin_connect#19] opened 2021-12-04 08:09 UTC
I tried to log in to my garmin account, but it always says 'Failed to connect'.I don't know if I'm missing something, but it just won't log into my account.

**Comment by BinnFudde** [comment] 2021-12-09 09:59
This issue seems to be a duplicate of #8. Sometimes the initial connect is failed, but give it some time or restarts.

**Comment by cyberjunky** [comment] 2021-12-24 15:03
Release 0.1.4 should work better.

**Closed** 2021-12-24 15:03 UTC
