### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by Strux-DK** [cyberjunky/home-assistant-garmin_connect#103] opened 2023-10-01 14:00 UTC
I had the same issue as [102](https://github.com/cyberjunky/home-assistant-garmin_connect/issues/102) so i tried the same remedy, by removing the integration, removing the download in HACS, redownloading it and reinstalling the integration, but am now at this error when trying to install it as an integration in home assistant.

**Comment by esmoyer** [comment] 2023-10-02 13:32
I get this same thing, it also messes up my Nest and Zwave integrations for some reason. Took me forever to figure out but it started last night after a reboot; did a full VM restore in Proxmox this morning, everything was working great but noticed the Garmin Connect was throwing an error. Did the work-around as in 102 and did another restart and boom, GarminConnect, Nest and Zwave all throwing this same error and won't load. 

Super weird.

**Comment by wimg** [comment] 2023-11-04 22:46
Having exactly the same issue. Tried uninstalling and reinstalling, but to no avail.

The full error in the logs is :
2023-11-04 23:45:18.859 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration garmin_connect: cannot import name 'TypeAliasType' from 'typing_extensions' (/usr/local/lib/python3.10/site-packages/typing_extensions.py)

**Comment by cyberjunky** [comment] 2023-11-21 09:42
Does this happens still with latest HA version?

**Comment by wimg** [comment] 2023-11-21 19:38
Sadly with the HA version 2023.4.2 the problem is still identical :

2023-11-21 20:36:41.437 ERROR (MainThread) \[homeassistant.config\_entries\] Error occurred loading flow for integration garmin\_connect: cannot import name 'TypeAliasType' from 'typing\_extensions' (/usr/local/lib/python3.10/site-packages/typing\_extensions.py)

**Comment by cyberjunky** [comment] 2023-11-22 12:32
Removed and reinstalled Garmin Connect a few times, I cannot reproduce this.
Maybe there is a conflict with another integration, which ones do you have installed?

**Comment by wimg** [comment] 2023-11-22 14:02
HACS integrations :

*   Waste Collection Schedule
*   Emporia Vue
*   Garmin Connect
*   HACS
*   Adaptive Lighting
*   Neerslag App

HACS frontend :

*   button-card
*   Neerslag Card
*   HA (Lovelace) Card Waze Travel Time

**Comment by cyberjunky** [comment] 2024-01-02 11:59
@Strux-DK @wimg @esmoyer although I didn't find/fixed anything specific to this error can you try the new version 0.2.19 and also update to latest HA version (if not done already)

If still an issue please enable debug log for garmin connect intergration and post relevant info (before and after the error) you can mask any uuid values if you want.

**Comment by wimg** [comment] 2024-01-02 13:19
Reinstalling fixed the issue for me with the latest version.

**Comment by cyberjunky** [comment] 2024-01-02 13:59
@wimg thanks, suspect for the others too, if not let me know, closing...

**Closed by cyberjunky** 2024-01-02 13:59 UTC
