### ISSUE TITLE
Getting warning messages about "The unit of this entity changed from '<unit>' to ''." after upgrading to HA 2022.5.x

### ISSUE THREAD

**Issue by Valdorama** [cyberjunky/home-assistant-garmin_connect#38] opened 2022-05-06 21:24 UTC
After upgrading to HA2022.5.x, the logs contain multiple warning for various sensors in this integration, to the effect that the unit of the entity has changed. e.g.: "The unit of this entity changed from 'min' to ''."

Clicking on the 'Fix Issue' link (Developer Tools -> Statistics) the following message is shown: 

> The unit of this entity changed, we can't store values in multiple units.
> If the historic statistic values have a wrong unit, you can update the units of the old values. The values will not be updated.
> Otherwise you can choose to delete all historic statistic values, and start over.

This affects various sensors with various units, such as 'min', '%', 'bpm' or 'steps', among others.

Wondering if this is a consequence of database optimizations/upgrades in the latest version of HA, and how best to proceed.

**Comment by cyberjunky** [comment] 2022-05-07 12:01
I saw it too, not yet clear what the issue is/what I have to change

**Comment by Valdorama** [comment] 2022-05-24 18:41
Thanks for the update. I installed 0.2.1 and there are no sensors from this integration that show as needing fixed. Looks like it's all working now.

**Comment by cyberjunky** [comment] 2022-05-24 18:47
Thanks for testing, closing for now...

**Closed by cyberjunky** 2022-05-24 18:47 UTC
